#!/usr/bin/env node

"use strict";

let fs = require("fs");
let config = require('./conf/config');

let inter = setInterval(() => {
    console.log('check cron.json');

    let appPath = process.env.APP_PATH;
    appPath = __dirname;
    if (!appPath) {
        return;
    }
    let cronFile = appPath + '/cron.json';
    if (!fs.existsSync(cronFile)) {
        return;
    }
    let content = fs.readFileSync(cronFile);
    if (content) {
        exec(content);
    }
}, 15000);


function exec(json) {
    config.name = process.env.APP_NAME;
    config.webhook = process.env.APP_MONITOR_HOOK;

    let data = JSON.parse(json);
    if (!data) {
        process.exit('json parse error');
    }

    if (data.hook) {
        config.webhook = data.hook;
    }

    if (data.jobs) {
        console.log('checked', data);
        clearInterval(inter);
        require('./service/task/server').start(data.jobs);
    }
}